name: preparar release

on: 
  create:
    branches:
      - release/**
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Set on JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Ejecucion Test Unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

      - name: Ejecucion Test API REST
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/*.jar
          retention-days: 1
